name: Driver
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    uses: KD131/cicd-integration-test-demo/.github/workflows/test_postgres.yml@main
    secrets: inherit

  deploy:
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: KD131/cicd-integration-test-demo/.github/workflows/deploy.yml@main
    secrets: inherit
